<a href="https://colab.research.google.com/github/pvitorinosantos/soulcode/blob/main/Fundamentos_de_Python(150623).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**FUNDAMENTOS DE PYTHON** :

Escola: SoulCode Academy

Curso: Bootcamp Analista de Dados - Martech AD2

Período: Semana 4

Professor: Franciane Rodrigues

Aluno: Paulo Vitorino dos Santos



*  Lógica de Programação: é a estruturação de conceitos e regras que orientam a execução do algoritmo.

*  Algoritmo: é a receita, ou seja, os comandos em um passo a passo claro e lógico, que conduzem as ações para a resolução de um problema ou para atingir determinados objetivos.

* Programa: é a implementação do algoritmo.

* **Lógica de programação:** é um conceito teórico que se refere à forma de pensar e abordar problemas de programação.

* **Algoritmo** é uma descrição abstrata de um processo ou solução que poderá ser executado por um computador;
* **Script** é um conjunto de instruções ou comandos escritos em uma linguagem de programação específica. Geralmente, os scripts são usados para automatizar tarefas ou para definir o comportamento de um programa ou sistema. Eles são frequentemente executados interpretando linha por linha, em vez de serem compilados em um programa executável separado.
* **Programa** é  um conjunto de instruções escritas em uma linguagem de programação específica, organizadas de forma lógica, para realizar uma tarefa ou resolver um problema específico. Ao contrário de um script, um programa é compilado ou interpretado antes da execução, resultando em um arquivo executável que pode ser executado diretamente em um sistema operacional.

##**Comentários e tipos básicos de dados**

In [ ]:
print ('Olá, Mundo!') # usando aspas simples
print ("Olá, Mundo!") # usando aspas duplas

Olá, Mundo!
Olá, Mundo!

In [ ]:
'''Isto é um comentário'''

'Isto é um comentário'

In [ ]:
"""Isto é um comentário"""

'Isto é um comentário'

In [ ]:
# Tipos de Dados

![Foto 1-150623.png]()

In [ ]:
# Estamos escrevendo nossos dados pessoais
print(51)         #int - quanti
print(1.72)       #float - quanti
print('Paulo')    #str escrita com aspas simples - quali
print("Santos")   #str escrita com aspas duplas  - quali
print(True)       #bool - quali (dummy/binária)

51
1.72
Paulo
Santos
True

**RESUMO**

*   Os **comentários** são como notas que você deixa para que você ou outra pessoa possa ler e ajuda documentar o seu código
*   **Comando print:** é uma função de saída utilizada em várias linguagens de
programação para exibir mensagens ou valores na tela do computador.
*   **\n**: usado para criar quebras de linha em um texto
*   Tipos de dados no Python mais usados são int, float, str, bool
*   int e float: dados quantitativos
*   str e bool: dados categóricos/qualitativos

##**Variáveis**

In [ ]:
# Estamos escrevendo nossos dados pessoais
print(51)         #int - quanti
print(1.72)       #float - quanti
print('Paulo')    #str escrita com aspas simples - quali
print("Santos")   #str escrita com aspas duplas  - quali
print(True)       #bool - quali (dummy/binária)

51
1.72
Paulo
Santos
True

In [ ]:
# Declarando as variáveis
idade = 51
altura = 1.72
nome = 'Paulo'
sobrenome = "Santos"
filhos = True

In [ ]:
# Imprimir na tela usando o comando Print
print(idade)
print(altura)
print(nome)
print(sobrenome)
print(filhos)

51
1.72
Paulo
Santos
True

In [ ]:
# Imprimir na tela usando apenas o nome da variável
# se somente invocarmos os nomes de 2 ou mais variáveis, será mostrado apenas o valor da última variável solicitada
idade
altura

1.72

In [ ]:
# Impressão geral na tela de todas as variáveis declaradas
print(idade, altura, nome, sobrenome, filhos)

51 1.72 Paulo Santos True

In [ ]:
# O comando TYPE serve para checarmos o tipo de dado que a variável está declarada
type(idade)

int

In [ ]:
# Checando o tipo de variável usando os comandos PRINT e TYPE juntos
print(type(idade))
print(type(altura))
print(type(nome))
print(type(sobrenome))
print(type(filhos))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>

In [ ]:
# Atenção: o Python é sensível às letras Maiúsculas e Minúsculas
nome = 'Paulo'
#print(Nome)

In [ ]:
# Armazenando strings e números
nome_completo = 'Paulo Vitorino'
numero_favorito = '43'

In [ ]:
# Checando a variável número favorito
print(type(numero_favorito))

<class 'str'>

In [ ]:
# SE o número estiver entre aspas, ele se transforma em uma string
print(nome_completo, numero_favorito)

Paulo Vitorino 43

In [ ]:
# Primeiro nome do nosso código
nome

'Paulo'

In [ ]:
# Renomeando a variável
# Atualização da variável Nome
# Sempre a última atualização é que será a válida (desde que o bloco tenha sido atualizado)
nome = 'Vitorino'

In [ ]:
nome

'Vitorino'

**Resumo**
*  **Variáveis** permitem salvar valores na memória usando um nome que atribuímos
* Declaramos um nome no lado esquerdo do operador igual (“=”), e no lado direito, atribuir o valor que queremos salvar para usar mais tarde.
* Como ler: Declaramos a variável "a" ao valor do "2" do tipo int
* **a = 2**
* Como ler: Declaramos a variável "b" ao valor do "10.953" do tipo float
* **b = 10.953**
* Como ler: A variável "a" recebe valor 2 do tipo int
* **a = 2**
* Como ler: A variável "b" recebe valor 10.953 do tipo float
* **b = 10.953**
* É possível usar os dois comandos print e type juntos
* Atenção: Número pode ser string

**Regras para nomes de variáveis**
* Deve começar com uma letra (maíuscula ou minúscula) ou subcrito(_).
* Nunca pode começar com um número.
* Pode conter letras maiúsculas, minúsculas, números e subscrito.
* Não pode-se utilizar como parte do nome de uma variável:
{ ( + - * / \ ; . , ?
* Letras maiúsculas e minúsculas são diferentes:
casa = 4
Casa = 4

##**Conversão de Variáveis**

In [ ]:
# Conversão de INT para FLOAT
num_int = 10
num_float = float(num_int)

In [ ]:
# Checando a conversão
print(type(num_int),type(num_float))
print(num_float)

<class 'int'> <class 'float'>
10.0

In [ ]:
# Conversão de INT para STRING
num_int = 10
num_str = str(num_int)

In [ ]:
# Checando a conversão
print(type(num_int),type(num_str))
print(num_str)

<class 'int'> <class 'str'>
10

In [ ]:
# Conversão de FLOAT para INT
num_float = 10.5
num_int = int(num_float)

In [ ]:
# Checando a conversão
print(type(num_float),type(num_int))
print(num_int)

<class 'float'> <class 'int'>
10

In [ ]:
# Conversão de FLOAT para STRING
num_float = 10.6
num_string = str(num_float)

In [ ]:
# Checando a Conversão
print(type(num_float),type(num_string))
print(num_string)

<class 'float'> <class 'str'>
10.6

In [ ]:
# Conversão de STRING para INT
num_string = '51'
num_int = int(num_string)

In [ ]:
# Checando a Conversão
print(type(num_string),type(num_int))
print(num_int)

<class 'str'> <class 'int'>
51

In [ ]:
# Conversão de STRING para FLOAT
num_string = '52'
num_float = float(num_string)

In [ ]:
# Checando a Conversão
print(type(num_string),type(num_float))
print(num_float)

<class 'str'> <class 'float'>
52.0

In [ ]:
# FALHA NO SISTEMA:
#Conversão de str para int ()
# num_str = '10.5'
# num_int = int(num_str)

# Conversão de str para int ()
num_str = '10.5'
num_float = float(num_str) # conversão intermediária
num_int = int(num_float)

# Checando
print(type(num_str), type(num_int))
print(num_int)

<class 'str'> <class 'int'>
10

##  **Operadores Matemáticos**

 Os operadores matemáticos básicos, tais como: adição, subtração, multiplicação, divisão, exponenciação e radiciação podem ser feitos dentro do Pythom

In [ ]:
#Adição
n1 = 5.887
n2 = 7.15
soma = n1+n2
print(soma)
print('A soma é: ',soma)
print(f'A soma dos números é {soma:.4f}')
print(n1+n2)
n1+n2

13.036999999999999
A soma é:  13.036999999999999
A soma dos números é 13.0370
13.036999999999999

13.036999999999999

In [ ]:
#Subtração
a1=154.587
a2=10.548
sub=a1-a2
print(sub)
print('A subtração é: ',sub)
print('A subtração é: ',round(sub,2))
print(f'A subtração dos números é {sub:.4f}')
print(a1-a2)
a1-a2

144.039
A subtração é:  144.039
A subtração é:  144.04
A subtração dos números é 144.0390
144.039

144.039

In [ ]:
#Multiplicação
b1=3.57
multi=b1*3
print(multi)
print('A multiplicação é: ',multi)
print('A multiplicação é: ',round(multi,2))
print(f'A multiplicação dos números é {multi:.4f}')
print(b1*3)
b1*3

10.709999999999999
A multiplicação é:  10.709999999999999
A multiplicação é:  10.71
A multiplicação dos números é 10.7100
10.709999999999999

10.709999999999999

In [ ]:
#Divisão
x1=10
x2=5
div=x1/x2
print(div)
print('A divisão é: ',div)
print('A divisão é: ',round(div,2))
print(f'A divisão dos números é {div:.4f}')
print(x1/x2)
x1/x2

2.0
A divisão é:  2.0
A divisão é:  2.0
A divisão dos números é 2.0000
2.0

2.0

### Estrutura de Condição - if, else, elif

Instrução IF:


*   A instrução IF é usada para executar um bloco de códigos se uma determinada condição for verdadeira. A sintaxe geral é a seguinte:

In [ ]:
'''
if condição:
  # bloco de código a ser executado se a condição for verdadeira
  '''

'\nif condição:\n  # bloco de código a ser executado se a condição for verdadeira\n  '

In [ ]:
idade = 19
if idade >=18:
  print('Você é maior de idade')

Você é maior de idade

In [ ]:
idade = 18
if idade >=18:
  print('Você é maior de idade')

Você é maior de idade

In [ ]:
idade = 17
if idade >=18:
  print('Você é maior de idade')

Instrução ELSE:


1.   A instrução ELSE é usada em conjunto com a instrução IF e especifica um bloco de código a ser executado se a condição do IF não for verdadeira. A sintaxe geral é a seguinte:

In [ ]:
'''
if condição:
  # bloco de código a ser executado se a condição for verdadeira
else:
  # bloco de código a ser executado se a condição não for verdadeira
  '''

'\nif condição:\n  # bloco de código a ser executado se a condição for verdadeira\nelse:\n  # bloco de código a ser executado se a condição não for verdadeira\n  '

In [ ]:
idade = int(input('Digite sua idade: '))

if idade >= 18:
  print('Você é maior de idade')
else:
  print('Você é menor de idade')

Digite sua idade: 5
Você é menor de idade

Instrução ELIF


*   A instrução ELIF é uma abreviação de "ELSE IF" e permite testar múltiplas condições em sequência. Ela é usada quando há mais de duas possibilidades a serem consideradas. A sintaxe geral é a seguinte:

In [ ]:
'''
if condição1:
  # bloco de código a ser executado se a condição 1 for verdadeira
elif condição2:
  # bloco de código a ser executado se a condição 2 for verdadeira
else:
  # bloco de código a ser executado se nenhuma das condições anteriores for verdadeira
  '''

'\nif condição1:\n  # bloco de código a ser executado se a condição 1 for verdadeira\nelif condição2:\n  # bloco de código a ser executado se a condição 2 for verdadeira\nelse:\n  # bloco de código a ser executado se nenhuma das condições anteriores for verdadeira\n  '

In [ ]:
nota = float(input('Digite sua nota: '))

if nota >=90:
  print('Sua nota é A')
elif nota >=80:
  print('Sua nota é B')
elif nota >=70:
  print('Sua nota é C')
else:
  print('Sua nota é D')

Digite sua nota: 65.4
Sua nota é D

Exemplo:


1.   Escreva um programa que verifique se um número digitado pelo usuário é positivo, negativo ou zero.

Passo a Passo:


1. Solicite ao usuário que digite um número.
2. Armazene o número digitado em uma variável chamada "número".
3. Verifique se o número digitado é zero. Se sim, exiba a mensagem "O número digitado é zero".
4. Caso contrário, verifique se o número é maior que zero. Se sim, exiba a mensagem "O número digitado é positivo."
5. Se nenhuma das condições anteriores for atendida, significa que o número é negativo. Nesse caso, exiba a mensagem "O número digitado é negativo."
6. Encerre o programa.

In [ ]:
num = float(input("Digite um número: "))

if num == 0:
    print("O número digitado é zero.")
elif num > 0:
    print("O número digitado é positivo.")
else:
    print("O número digitado é negativo.")

Digite um número: 5
O número digitado é positivo.

# Atividades

In [ ]:
# 1. Faça um algoritmo que leia um número inteiro e diga se ele é maior, menor ou igual a 10;

In [ ]:
num = float(input('Digite um número inteiro: '))
if num == 10:
  print('Esse número é IGUAL a 10')
elif num < 10:
  print('Esse número é MENOR do que 10')
else:
  print('Esse número é MAIOR do que 10')

Digite um número inteiro: 9.9
Esse número é MENOR do que 10

In [ ]:
# 2. Faça um algoritmo que leia dois números inteiros e apresente na tela o maior deles ou se eles são iguais;

In [ ]:
num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite o segundo  número: '))
if num1 == num2:
  print('Esses números SÃO IGUAIS')
elif num1 > num2:
  print('O primeiro número é MAIOR do que o segundo número')
else:
  print('O primeiro número é MENOR do que o segundo número')

Digite o primeiro número: 9
Digite o segundo  número: 9.9
O primeiro número é MENOR do que o segundo número

In [ ]:
# 3. Crie um algoritmo que leia um número e diga se ele está no intervalo fechado entre 25 e 200;
num = float(input('Digite um número: '))
if num >=25 and num <= 200:
  print('Este número ESTÁ CONTIDO no intervalo entre 25 e 200')
else:
  print('Este número NÃO ESTÁ CONTIDO no intervalo entre 25 e 200')

Digite um número: 155
Este número ESTÁ CONTIDO no intervalo entre 25 e 200

In [ ]:
# 4. Crie um algoritmo que leia um número e informe na tela se o mesmo é positivo. Caso seja, mostre o número na tela;
num = float(input('Digite um número: '))
if num > 0:
  print('Este número é POSITIVO --->', num)
elif num <0:
  print('Este número é NEGATIVO')
else:
  print('Você digitou ZERO')

Digite um número: 5
Este número é POSITIVO ---> 5.0

In [ ]:
# 5. Crie um algoritmo que leia um número e informe se ele é divisível por 7.
num = float(input('Digite um número: '))
if num %7 == 0:
  print('Esse número É DIVISÍVEL por 7')
else:
  print('Esse número NÃO É DIVISÍVEL por 7')

Digite um número: 7
Esse número É DIVISÍVEL por 7

In [ ]:
# 6. Crie um algoritmo que leia um número e diga se ele é par ou ímpar.
num = int(input('Digite um número: '))
if num %2 == 0:
  print('Esse número É PAR')
else:
  print('Esse número NÃO É PAR')

Digite um número: 455
Esse número NÃO É PAR

In [ ]:
# 7. Escreva um programa em Python que solicite ao usuário que digite uma letra. Em seguida, verifique se a letra digitada é uma vogal ou não.
txt = str(input('Digite uma letra: '))
txt = txt.upper()
if txt == 'A' or txt == 'E' or txt == 'I' or txt =='O' or txt == 'U':
  print('Esse letra É uma vogal')
else:
  print('Essa letra NÃO É uma vogal')

Digite uma letra: i
Esse letra É uma vogal

In [ ]:
# 8. Escreva um programa que solicite ao usuário três notas de um aluno e calcule a média. Em seguida, exiba a média e uma mensagem informando se o aluno foi aprovado
#(média maior ou igual a 7) ou reprovado.
num1 = float(input('Digite a primeira nota: '))
num2 = float(input('Digite a segunda nota : '))
num3 = float(input('Digite a terceira nota: '))
med= float((num1)+(num2)+(num3))/3
if med >= 7:
  print(f'O aluno foi APROVADO, com a média {med:.2f}')
else:
  print(f'O aluno foi REPROVADO, com a média {med:.2f}')

Digite a primeira nota: 7
Digite a segunda nota : 7
Digite a terceira nota: 6
O aluno foi REPROVADO, com a média 6.67

In [ ]:
# 9. Escreva um programa que solicite ao usuário os comprimentos dos três lados de um triângulo. Em seguida, exiba uma mensagem informando se o triângulo é equilátero
#(todos os lados iguais), isósceles (dois lados iguais) ou escaleno (todos os lados diferentes).
lado1 = int(input('Digite o comprimento do 1o lado do triângulo: '))
lado2 = int(input('Digite o comprimento do 2o lado do triângulo: '))
lado3 = int(input('Digite o comprimento do 3o lado do triângulo: '))
if lado1 < (lado2 + lado3) and lado2 < (lado1 + lado3) and lado3 < (lado1 + lado2):
  tri = True
else:
  tri = False
if tri == True:
  print('As medidas informadas FORMAM um triângulo.')
else:
  print('As medidas informadas NÃO FORMAM um triângulo')
if tri == True:
  if lado1 == lado2 and lado2 == lado3:
    print('Este é um triângulo EQUILÁTERO')
  elif lado1 != lado2 and lado2 == lado3:
    print('Este é um triângulo ISÓSCELES')
  elif lado1 == lado3 and lado1 != lado2:
    print('Este é um triângulo ISÓSCELES')
  elif lado1 == lado2 and lado1 != lado3:
    print('Este é um triângulo ISÓSCELES')
  else:
    print('Este é um triângulo ESCALENO')
else:
  pass

Digite o comprimento do 1o lado do triângulo: 5
Digite o comprimento do 2o lado do triângulo: 10
Digite o comprimento do 3o lado do triângulo: 14
As medidas informadas FORMAM um triângulo.
Este é um triângulo ESCALENO

In [ ]:
# 10.  Escreva um programa que solicite ao usuário sua idade e exiba uma mensagem informando em qual faixa etária ele se encontra: criança (0-12 anos), adolescente (13-17 anos),
#adulto (18-59 anos) ou idoso (60 anos ou mais).
num = int(input('Digite sua idade: '))
if num <= 12:
  print('Você é uma CRIANÇA')
elif 13 <= num <= 17:
  print('Você é um ADOLESCENTE')
elif 18 <= num <= 59:
  print('Você é um ADULTO')
else:
  print('Você é um IDOSO - Vá descansar!')

Digite sua idade: 60
Você é um IDOSO - Vá descansar!

# Estrutuas de Dados em Python


1.   Parte 1 - Listas

In [ ]:
# Lista é uma estrutura que pode armazenar diversos valores sobre um determinado atributo
lista_vazia =  []
noivo = ['Zé', 'Mané', 'Ana', 'Franciane', 'João', 'Franz']
print(f'Convidados do noivo - {noivo}')
idades = [41, 47, 46, 28, 17, 50]
print(f'Idade dos convidados do noivo = {idades}')
massas = [86, 74, 52, 47, 90, 110]
alturas = [1.68, 1.74, 1.65, 1.65, 1.80, 1.97]
print(f'Massas dos convidados do noivo = {massas}')
print(f'Alturas dos convidados do noivo = {alturas}')

Convidados do noivo - ['Zé', 'Mané', 'Ana', 'Franciane', 'João', 'Franz']
Idade dos convidados do noivo = [41, 47, 46, 28, 17, 50]
Massas dos convidados do noivo = [86, 74, 52, 47, 90, 110]
Alturas dos convidados do noivo = [1.68, 1.74, 1.65, 1.65, 1.8, 1.97]
Franciane

In [ ]:
# Acessando um elemento específico da lista a partir do seu índice
print(f'A convidade de honra é {noivo[3]}')
# Criar uma sublista com apenas os três primeiros elementos da lista noivo
sublista = noivo[:3]
print(sublista)
print(f'O primeiro convidado é {noivo[0]} e o último convidado é {noivo[-1]}')
print(f'{noivo}')

A convidade de honra é Franciane
['Zé', 'Mané', 'Ana']
O primeiro convidado é Zé e o último convidado é Franz
['Zé', 'Mané', 'Ana', 'Franciane', 'João', 'Franz']

In [ ]:
# Método index (valor procurado, índice de início da procura e índice do fim da procura) por definição se não for oferecido o índice
id=noivo.index('Franciane')

In [ ]:
# Qual é o IMC da convidada Fran?
print(f'O IMC da Fran é {(massas[id]/alturas[id]**2):.2f}')

O IMC da Fran é 17.26

Desafio 1: Crir um programa que receba do usuário um nome e caso esse nome esteja na lista, guarde seu índice em uma variável e a utilize buscar massa e altura correspondente, bem como calcular seu IMC e após tudo isso informar o usuário. Caso o nome não esteja na lista, retorne uma mensagem informando o usuário,

In [ ]:
nome = str(input('Digite o nome que deseja consultar: ')) # Recebendo o nome do usuário
noivo = ['Zé', 'Mané', 'Ana', 'Fran', 'João', 'Franz'] # Cria o banco de dados com os nomes dos convidados do noivo
nome = nome.capitalize() # Deixo o nome que o usuário digitou com a primeira letra em caixa alta e as demais em caixa baixa
if nome in noivo: #se o nome que o usuário digitou estiver no banco de dados, faça algo
  id2 = noivo.index(nome) # Recebendo o argumento nome e procurando o seu índice, já sabendo que ele está na lista exatamente como digitado
  imc = massas[id2]/alturas[id2]**2 # Calculando o IMC já sabendo a posição que deve buscar em cada lista (massas e alturas)
  print(f'{nome} tem {massas[id2]} kg, {alturas[id2]} metro(s) e seu IMC é: {imc:.1f}')
else:
  print(f'Desculpe, {nome} não está na lista. Por favor, reinicie o programa para consultar outro nome')

Digite o nome que deseja consultar: Paulo
Desculpe, Paulo não está na lista. Por favor, reinicie o programa para consultar outro nome

In [ ]:
#  Adicionando elementos em uma lista qualquer com o método append (). Por padrão, este método insere o valor desejado em uma lista existente na última posição
lista_vazia = [] # Cria uma lista vazia com o nome lista vazia e apaga todos os elementos de qualquer objeto com o mesmo nome
print(lista_vazia) # Imprime uma lista vazia que já existe
lista_vazia.append('Joana') # Adiciona Joana na última posição de uma lista que já exista
lista_vazia.append('Douglas')
lista_vazia.append('Eduardo')
lista_vazia.append('Ester')
lista_vazia.append('Daniela')
lista_vazia.append('Pedro')
lista_vazia.append('Maria')
print(lista_vazia) # Imprime o status atual da lista vazia
fam = lista_vazia
print(lista_vazia)
print(fam)

[]
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']

In [ ]:
fam.insert(3,'Tobias')
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Tobias', 'Ester', 'Daniela', 'Pedro', 'Maria']

In [ ]:
fam[3] = 'Raimundo' #Atribuição Direta - insere um novo elemento, substituindo o anterior, se houver
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Raimundo', 'Ester', 'Daniela', 'Pedro', 'Maria']

In [ ]:
# Excluindo elementos de uma lista
fam.pop() # Método que exclui pelo índice. Por padrão, exclui o último elemento se não informarmos o índice
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Raimundo', 'Ester', 'Daniela', 'Pedro']

In [ ]:
# Excluir Joana da lista fam pelo método pop
fam.pop(0)
print(fam)

['Douglas', 'Eduardo', 'Raimundo', 'Ester', 'Daniela', 'Pedro']

In [ ]:
# Excluir Raimundo da lista fam pelo método remove
fam.remove('Raimundo')
print(fam)

['Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro']